### ISSUE TITLE
unhandled exception: JIT compilation failed with Nim 2.2.8

### ISSUE THREAD

**Issue by ButteredCats** [zedeus/nitter#1385]
Trying to build with Nim 2.2.8 gives many warnings about "Package x lists an underspecified version of y" and `Warning: 'Lock levels' are deprecated, now a noop`.

After compliation Nitter refuses to start, saying:
```
re.nim(80)               raiseInvalidRegex
Error: unhandled exception: JIT compilation failed. [RegexError]
```

**Comment by guneykabel** [comment]
I was able to reproduce this, seems like Nim 2.2.8 has changed stuff on their end.

### Issue
Nim 2.2.8's re module switched from PCRE1 to PCRE2, which is stricter about character class ranges. The actual error is PCRE2_ERROR_CLASS_INVALID_RANGE (code 150) not a JIT issue.

The problem is `\w-_` inside character classes. PCRE2 reads that as a range from `\w` to `_`, which isn't valid.

### Fix

[`src/parserutils.nim:19`](https://github.com/zedeus/nitter/blob/master/src/parserutils.nim#L19)  escape the hyphen:
`htRegex = re"(^|[^\w\-_./?])([#$]|＃)([\w_]+)"`

[`src/experimental/parser/user.nim:11`](https://github.com/zedeus/nitter/blob/master/src/experimental/parser/user.nim#L11) same fix:
`htRegex = nre.re"""(*U)(^|[^\w\-_.?])([#＃$])([\w_]*+)(?!</a>|">|#)"""`

Escaping the hyphen in both character classes should do the trick.

**Comment by ButteredCats** [comment]
This has been fixed since https://github.com/zedeus/nitter/commit/a86be15f852eadfd95b7441db97f1605a709e768, thanks!
